/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import DAO.EnderecoDAO;
import DAO.FuncionariosDAO;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;


/**
 *
 * @author wilsi
 */
public class InserirFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form InserirFuncionarioView
     */
    public InserirFuncionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator = new javax.swing.JSeparator();
        lTitulo = new javax.swing.JLabel();
        lsubTitulo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lCpf = new javax.swing.JLabel();
        lDataNasc = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        lBairro = new javax.swing.JLabel();
        lCidade = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lRg = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        lTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lCep = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JLabel();
        bSalvar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        txtRg = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 10));

        lTitulo.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(204, 0, 0));
        lTitulo.setText("SisAC");
        jPanel1.add(lTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lsubTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lsubTitulo.setForeground(new java.awt.Color(153, 0, 0));
        lsubTitulo.setText("Funcionário do acolhimento");
        jPanel1.add(lsubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        lNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lNome.setForeground(new java.awt.Color(255, 255, 255));
        lNome.setText("Nome");
        jPanel1.add(lNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lCpf.setForeground(new java.awt.Color(255, 255, 255));
        lCpf.setText("CPF");
        jPanel1.add(lCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lDataNasc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        lDataNasc.setText("Data de Nasc.");
        jPanel1.add(lDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lEmail.setForeground(new java.awt.Color(255, 255, 255));
        lEmail.setText("Email");
        jPanel1.add(lEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        lEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lEndereco.setText("Endereço");
        jPanel1.add(lEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        lBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lBairro.setForeground(new java.awt.Color(255, 255, 255));
        lBairro.setText("Bairro");
        jPanel1.add(lBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lCidade.setForeground(new java.awt.Color(255, 255, 255));
        lCidade.setText("Cidade");
        jPanel1.add(lCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        lTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lTipo.setForeground(new java.awt.Color(255, 255, 255));
        lTipo.setText("Tipo");
        jPanel1.add(lTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 410, -1));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, -1));

        lRg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lRg.setForeground(new java.awt.Color(255, 255, 255));
        lRg.setText("RG");
        jPanel1.add(lRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        jPanel1.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, -1));

        lTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lTelefone.setText("Telefone");
        jPanel1.add(lTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 410, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, -1));

        lNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lNumero.setForeground(new java.awt.Color(255, 255, 255));
        lNumero.setText("Nº");
        jPanel1.add(lNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 410, -1));
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, -1));

        lCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lCep.setForeground(new java.awt.Color(255, 255, 255));
        lCep.setText("CEP");
        jPanel1.add(lCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auxiliar", "Coordenador", "Tecnico" }));
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 80, -1));

        txtStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Status");
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        bSalvar.setBackground(new java.awt.Color(204, 204, 204));
        bSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 90, -1));

        bCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bCancelar.setText("Cancelar");
        jPanel1.add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));
        jPanel1.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, -1));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 140, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 50, -1));
        jPanel1.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 150, -1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", " " }));
        jPanel1.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        
        FuncionariosDAO funcionario = new FuncionariosDAO();
        EnderecoDAO endereco = new EnderecoDAO();
        
        try {
            
            //Inserindo Endereço
            endereco.setEndereco(txtEndereco.getText());
            endereco.setNumEnd(Integer.parseInt(txtNumero.getText()));
            endereco.setBairro(txtBairro.getText());
            endereco.setCidade(txtCidade.getText());
            endereco.setCep(Double.parseDouble(txtCep.getText()));
            endereco.setEndereco();
            //Fim da inserção do endereço
            
            funcionario.setCpfFunc(Double.parseDouble(txtCpf.getText()));
            funcionario.setNomeFunc(txtNome.getText());
            funcionario.setRgFunc(Double.parseDouble(txtRg.getText()));            
            
            SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date dutiln;
            dutiln = form.parse(txtDataNasc.getText());
            java.sql.Date dsqln = new java.sql.Date(dutiln.getTime());

            funcionario.setDataNascFunc(dsqln);
            
            funcionario.setTelefoneFunc(txtTelefone.getText());             
            funcionario.setEmailFunc(txtEmail.getText());
            funcionario.setTipoFunc((String) cbTipo.getSelectedItem());            
            funcionario.setStatusFunc((String) cbStatus.getSelectedItem());
            funcionario.setIdEndereco_FK(endereco.getUltimoEndereco());
            
            funcionario.setFuncionario();
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_bSalvarActionPerformed

    public void editarFuncionario(long cpfFunc){
        
        this.setVisible(true);
        
        FuncionariosDAO funcionario;
        funcionario = new FuncionariosDAO().getFuncionario(cpfFunc);
        
        EnderecoDAO endereco;
        endereco = new EnderecoDAO().getEndereco(funcionario.getIdEndereco_FK());
        
        txtCpf.setEditable(false);
        txtCpf.setText(String.valueOf(funcionario.getCpfFunc()));
        
        txtNome.setText(String.valueOf(funcionario.getNomeFunc()));
        txtRg.setText(String.valueOf(funcionario.getRgFunc()));
        
        SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
        
        
        txtTelefone.setText(String.valueOf(funcionario.getTelefoneFunc()));
        txtEmail.setText(String.valueOf(funcionario.getEmailFunc()));
        
        for(int i = 0; i < cbTipo.getItemCount(); i++){
            if(cbTipo.getItemAt(i).equals(funcionario.getTipoFunc())){
                cbTipo.setSelectedIndex(i);
            }
        }
        
        for(int i = 0; i < cbStatus.getItemCount(); i++){
            if(cbStatus.getItemAt(i).equals(funcionario.getStatusFunc())){
                cbStatus.setSelectedIndex(i);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirFuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bSalvar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lBairro;
    private javax.swing.JLabel lCep;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lDataNasc;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lRg;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lsubTitulo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRg;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
